# AMS 691 Fall 2020 Project 2

Greeshma Balabhadra
112750309

### Testing Project1 (Bar Sampler) and Project2 functionalities

In [1]:
import pandas as pd
import numpy as np
import Project1 as bs
import Project2 as es

In [2]:
## Get the file name and preprocess the data for required stocks 
## Store the tick data into csv file for future use

# filepath = 'EQY_US_ALL_TRADE_20191008'
# bs.preProcessDataintoCSV(filepath)
# tdata = pd.read_csv(filepath+'.csv', delimiter='|')
# AAPL = bs.getTicksDataForaSymbol(tdata, 'AAPL')
# AMZN = bs.getTicksDataForaSymbol(tdata, 'AMZN')
# MSFT = bs.getTicksDataForaSymbol(tdata, 'MSFT')

# AMZN.to_csv('AMZN.csv')
# AAPL.to_csv('AAPL.csv')
# MSFT.to_csv('MSFT.csv')

#### Read Data from stock CSV files into Pandas Data Frame

In [3]:
AMZNdf = pd.read_csv("./AMZN.csv").iloc[:,1:]
AAPLdf = pd.read_csv("./AAPL.csv").iloc[:,1:]
MSFTdf = pd.read_csv("./MSFT.csv").iloc[:,1:]

In [4]:
AMZNdf.head(2)

Time Exchange Symbol Sale Condition  Trade Volume  Trade Price  \
0  40000031614134        P   AMZN           @ TI             5      1732.86   
1  40008758072535        Q   AMZN           @FTI            10      1732.02   

   Trade Stop Stock Indicator  Trade Correction Indicator  Sequence Number  \
0                         NaN                           0             1145   
1                         NaN                           0             1152   

   Trade Id Source of Trade Trade Reporting Facility  Participant Timestamp  \
0         1               N                                  40000029500672   
1         1               N                                  40008758049797   

   Trade Reporting Facility TRF Timestamp  Trade Through Exempt Indicator  
0                                     NaN                               0  
1                                     NaN                               1

In [5]:
## Clean data i.e Delete trades outside trading hours ( given Time Period ) or for given tradeType 
timePeriod = ["1900-01-01 09:30:00", "1900-01-01 16:00:00"]
AMZN = es.cleanData(AMZNdf, tradeType = None, timePeriod = timePeriod)
AAPL = es.cleanData(AAPLdf, tradeType = None, timePeriod = timePeriod)
MSFT = es.cleanData(MSFTdf, tradeType = None, timePeriod = timePeriod)

In [6]:
AMZN.head(2)

Exchange Symbol Sale Condition  Trade Volume  \
Date_Time                                                                    
1900-01-01 09:30:00.113432261        Y   AMZN           @  I             7   
1900-01-01 09:30:00.165981559        Q   AMZN           @FTI            12   

                               Trade Price  Trade Stop Stock Indicator  \
Date_Time                                                                
1900-01-01 09:30:00.113432261      1721.02                         NaN   
1900-01-01 09:30:00.165981559      1722.49                         NaN   

                               Trade Correction Indicator  Sequence Number  \
Date_Time                                                                    
1900-01-01 09:30:00.113432261                           0            13612   
1900-01-01 09:30:00.165981559                           0            13732   

                               Trade Id Source of Trade  \
Date_Time                                                 
1900-01-01 09:30:00.113432261         6               N   
1900-01-01 09:30:00.165981559       288               N   

                              Trade Reporting Facility  Participant Timestamp  \
Date_Time                                                                       
1900-01-01 09:30:00.113432261                                  93000113220000   
1900-01-01 09:30:00.165981559                                  93000165953740   

                               Trade Reporting Facility TRF Timestamp  \
Date_Time                                                               
1900-01-01 09:30:00.113432261                                     NaN   
1900-01-01 09:30:00.165981559                                     NaN   

                               Trade Through Exempt Indicator  
Date_Time                                                      
1900-01-01 09:30:00.113432261                               0  
1900-01-01 09:30:00.165981559                               1

#### Creating Minute Bars using Bar Sampler

Use the functions you developed in project 1 to sample 1-minute bars for 3 stocks of your choosing(keep in mind the code needs to work for any 3 stocks). Use the functions developed above to create a db structure for log returns and one for trade volume.

In [7]:
## bs.minuteBarsResampler takes the filtered dataframe for any stock and creates minute bar sampler
AMmbsdf = bs.minuteBarsResampler(AMZN, units = 'T', size = 1, volume = True).reset_index()
APmbsdf = bs.minuteBarsResampler(AAPL, units = 'T', size = 1, volume = True).reset_index()
MSmbsdf = bs.minuteBarsResampler(MSFT, units = 'T', size = 1, volume = True).reset_index()

In [8]:
## Renaming columns to be consistent with the barSampler outputs
AMmbs = AMmbsdf.rename(columns = {"open":"Open", "high":"High", "low":"Low", "close":"Close"})
APmbs = APmbsdf.rename(columns = {"open":"Open", "high":"High", "low":"Low", "close":"Close"})
MSmbs = MSmbsdf.rename(columns = {"open":"Open", "high":"High", "low":"Low", "close":"Close"})

In [9]:
AMmbs.head(2)

Date_Time     Open       High      Low      Close  Trade Volume
0 1900-01-01 09:30:00  1721.02  1722.4900  1717.71  1718.6300         67763
1 1900-01-01 09:31:00  1718.60  1719.2599  1717.05  1717.9502         12760

In [10]:
APmbs.head(2)

Date_Time    Open    High     Low   Close  Trade Volume
0 1900-01-01 09:30:00  225.88  226.30  225.58  226.29        693802
1 1900-01-01 09:31:00  226.30  226.61  225.87  226.33        165825

In [11]:
## Get the  logreturn for Minute bar samplers
AMmbslret = es.get_log_return(AMmbs).set_index('Date_Time')
APmbslret = es.get_log_return(APmbs).set_index('Date_Time')
MSmbslret = es.get_log_return(MSmbs).set_index('Date_Time')

In [12]:
AMmbslret.head(2)

Open       High      Low      Close  Trade Volume  \
Date_Time                                                                   
1900-01-01 09:30:00  1721.02  1722.4900  1717.71  1718.6300         67763   
1900-01-01 09:31:00  1718.60  1719.2599  1717.05  1717.9502         12760   

                     log returns  
Date_Time                         
1900-01-01 09:30:00    -0.001390  
1900-01-01 09:31:00    -0.000378

### Create Db - For Trade Volume and Log returns

In [13]:
## symbol <- list of stock tickers as an input to create the db structure
## createdb tales logreturns db (OHLCV + log rets), stock ticker list and db type ('log returns' or 'Trade Volume')
symbol = ['AAPL', 'AMZN', 'MSFT']
dbLogReturns = es.createdb([APmbslret, AMmbslret, MSmbslret], symbol, 'log returns')
print(dbLogReturns)

[DatetimeIndex(['1900-01-01 09:30:00', '1900-01-01 09:31:00',
               '1900-01-01 09:32:00', '1900-01-01 09:33:00',
               '1900-01-01 09:34:00', '1900-01-01 09:35:00',
               '1900-01-01 09:36:00', '1900-01-01 09:37:00',
               '1900-01-01 09:38:00', '1900-01-01 09:39:00',
               ...
               '1900-01-01 15:50:00', '1900-01-01 15:51:00',
               '1900-01-01 15:52:00', '1900-01-01 15:53:00',
               '1900-01-01 15:54:00', '1900-01-01 15:55:00',
               '1900-01-01 15:56:00', '1900-01-01 15:57:00',
               '1900-01-01 15:58:00', '1900-01-01 15:59:00'],
              dtype='datetime64[ns]', name='Date_Time', length=390, freq=None), ['AAPL', 'AMZN', 'MSFT'], array([[ 0.00181348, -0.00138968, -0.00277555],
       [ 0.00013256, -0.00037817,  0.00175387],
       [ 0.0011485 ,  0.00122188,  0.00196944],
       ...,
       [-0.00048984, -0.00110733, -0.00044189],
       [ 0.00095716,  0.00029893,  0.00029459],
       [-0.

/Users/greeshmab/Google Drive/SEM3/691.03/Project2.py:129: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  res.append(np.vstack((np.array(db[Metric]) for db in listdb)).T)


In [14]:
## Db structure for Trade Volume
dbTradeVolume = es.createdb([APmbslret, AMmbslret, MSmbslret], symbol, 'Trade Volume')
print(dbTradeVolume)

[DatetimeIndex(['1900-01-01 09:30:00', '1900-01-01 09:31:00',
               '1900-01-01 09:32:00', '1900-01-01 09:33:00',
               '1900-01-01 09:34:00', '1900-01-01 09:35:00',
               '1900-01-01 09:36:00', '1900-01-01 09:37:00',
               '1900-01-01 09:38:00', '1900-01-01 09:39:00',
               ...
               '1900-01-01 15:50:00', '1900-01-01 15:51:00',
               '1900-01-01 15:52:00', '1900-01-01 15:53:00',
               '1900-01-01 15:54:00', '1900-01-01 15:55:00',
               '1900-01-01 15:56:00', '1900-01-01 15:57:00',
               '1900-01-01 15:58:00', '1900-01-01 15:59:00'],
              dtype='datetime64[ns]', name='Date_Time', length=390, freq=None), ['AAPL', 'AMZN', 'MSFT'], array([[693802,  67763, 717640],
       [165825,  12760, 154339],
       [127813,  15063, 120464],
       ...,
       [174728,  32251, 207354],
       [158433,  39919, 322883],
       [314784,  41476, 561364]])]


In [15]:
## CCheck the structure of dblogreturns[2]
dbLogReturns[2].transpose()

array([[ 0.00181348,  0.00013256,  0.0011485 , ..., -0.00048984,
         0.00095716, -0.00151407],
       [-0.00138968, -0.00037817,  0.00122188, ..., -0.00110733,
         0.00029893, -0.00090854],
       [-0.00277555,  0.00175387,  0.00196944, ..., -0.00044189,
         0.00029459, -0.00110509]])

### Exponential Smoothing
Apply your smoothing function to the 1-minute bar db structure to normalize the volatility as close as possible to 1.Return a db structure containing these smoothed log returns.

In [16]:
## es.exponentialSmoothing 
## https://en.wikipedia.org/wiki/Exponential_smoothing

mnVarSmoothedLogReturns = []
for i in range(3):
    VarSmoothed = (dbLogReturns[2].transpose()[i][1:-1])/np.sqrt(es.exponentialSmoothing(dbLogReturns[2].transpose()[i][0:-2]**2,
                                                                                         lambda_=0.015))

    mnVarSmoothedLogReturns.append(VarSmoothed)
mnVarSmoothedLogReturnsm = np.array(mnVarSmoothedLogReturns)
print(np.std(mnVarSmoothedLogReturnsm, axis = 1))

[1.18653727 0.94209108 1.00072452]


In [17]:
##  db structure containing these smoothed log returns
dbSmoothedLogReturnsm = [dbLogReturns[0][:mnVarSmoothedLogReturnsm.shape[1]], dbLogReturns[1], 
                         mnVarSmoothedLogReturnsm.T]
print(dbSmoothedLogReturnsm)

[DatetimeIndex(['1900-01-01 09:30:00', '1900-01-01 09:31:00',
               '1900-01-01 09:32:00', '1900-01-01 09:33:00',
               '1900-01-01 09:34:00', '1900-01-01 09:35:00',
               '1900-01-01 09:36:00', '1900-01-01 09:37:00',
               '1900-01-01 09:38:00', '1900-01-01 09:39:00',
               ...
               '1900-01-01 15:48:00', '1900-01-01 15:49:00',
               '1900-01-01 15:50:00', '1900-01-01 15:51:00',
               '1900-01-01 15:52:00', '1900-01-01 15:53:00',
               '1900-01-01 15:54:00', '1900-01-01 15:55:00',
               '1900-01-01 15:56:00', '1900-01-01 15:57:00'],
              dtype='datetime64[ns]', name='Date_Time', length=388, freq=None), ['AAPL', 'AMZN', 'MSFT'], array([[ 0.07309635, -0.27212805,  0.63190179],
       [ 0.63808981,  0.88542709,  0.71278583],
       [ 0.02463086,  0.79312475,  0.54221814],
       ...,
       [ 0.22133005,  0.01305788,  0.23544292],
       [-0.4905023 , -1.71588804, -0.47434491],
       [ 0.

### Tick resampler and Exponential Smoothing

In [18]:
## es.tickResamplerAlignDatapoints takes Stock ticks dataframe, 
## datapoints - number of datapoints in the resampled dataframe based on ticks as inputs
## Here all the three stock dataframes return 1000 datapoints to align the calendar

datapoints = 1000
AMtbs =  es.tickResamplerAlignDatapoints(AMZN, datapoints, volume = True).reset_index()
APtbs =  es.tickResamplerAlignDatapoints(AAPL, datapoints, volume = True).reset_index()
MStbs =  es.tickResamplerAlignDatapoints(MSFT, datapoints, volume = True).reset_index()

AMtbslret = es.get_log_return(AMtbs)
APtbslret = es.get_log_return(APtbs)
MStbslret = es.get_log_return(MStbs)

#### Create Db for Tickresampled log returns

In [19]:
## symbol <- list of stock tickers as an input to create the db structure
## createdb tales logreturns db (OHLCV + log rets), stock ticker list and db type ('log returns' or 'Trade Volume')
symbol = ['AAPL', 'AMZN', 'MSFT']
dbLogReturnst = es.createdb([ APtbslret, AMtbslret, MStbslret], symbol, 'log returns')

In [20]:
print(dbLogReturnst)

[RangeIndex(start=0, stop=1000, step=1), ['AAPL', 'AMZN', 'MSFT'], array([[-4.42722745e-05,  5.69267693e-04, -6.56670703e-04],
       [ 3.54123327e-04,  0.00000000e+00,  0.00000000e+00],
       [ 3.09755075e-04, -3.19523158e-04,  0.00000000e+00],
       ...,
       [-6.67839120e-04, -2.16966169e-04, -7.36675384e-05],
       [ 4.22988307e-04,  2.75615372e-04, -4.42119232e-04],
       [-1.11351146e-03, -1.05550799e-04, -1.47416526e-04]])]


#### Exponential Smoothing tick bar db structure to normalize the volatility 

In [21]:
## es.exponentialSmoothing 
## https://en.wikipedia.org/wiki/Exponential_smoothing
mnVarSmoothedLogReturns = []
for i in range(3):
    VarSmoothed = (dbLogReturnst[2].transpose()[i][1:-1])/np.sqrt(es.exponentialSmoothing(dbLogReturnst[2].transpose()[i][0:-2]**2,
                                                                                         lambda_=0.045))
    mnVarSmoothedLogReturns.append(VarSmoothed)
mnVarSmoothedLogReturnst = np.array(mnVarSmoothedLogReturns)

## Print standard deviation of smoothed log returns for tick resampled  data
print(np.std(mnVarSmoothedLogReturnst, axis = 1))

[1.1318366  0.99536173 0.99910307]


In [22]:
##  db structure containing these smoothed tick sampled log returns
dbSmoothedLogReturnst = [dbLogReturnst[0][:mnVarSmoothedLogReturnst.shape[1]], dbLogReturnst[1], 
                         mnVarSmoothedLogReturnst.T]
print(dbSmoothedLogReturnst)

[RangeIndex(start=0, stop=998, step=1), ['AAPL', 'AMZN', 'MSFT'], array([[ 7.99876065,  0.        ,  0.        ],
       [ 3.57317626, -0.57435991,  0.        ],
       [-1.9271371 , -1.17967961, -0.58164867],
       ...,
       [ 0.05308941,  0.38888121,  0.        ],
       [-2.32888993, -1.08676809, -0.31692563],
       [ 1.34704966,  1.37494766, -1.94175136]])]
